### ISSUE TITLE
Feature: Support Hot Reloading Using 

### ISSUE THREAD

**Issue by roshaans** [near/bos-loader#17]
Bos-workspaces uses web sockets in order to enable hot-reloading. If bos-loader could do something simlar, it would make for a way better local development experience. 

[Bos Workspace Websocket PR: ](https://github.com/NEARBuilders/bos-workspace/pull/16)
[Bos Workspace Websocket Code: 
](https://github.com/NEARBuilders/bos-workspace/blob/8c541a749ac886dd9bfb73fd5fe62cfe44014248/gateway/src/useRedirectMap.js#L10)

**Comment by charleslavon** [comment]
This is now supportied in [roc-components](https://github.com/near/near-roc-components?tab=readme-ov-file#local-development)
